// Vocabulary data for WordPop!
// Each entry: { word, emoji, theme }
// Rules: `word` is lowercase a-z only (no spaces/hyphens), concrete & picturable,
// beginner-friendly (CEFR A1-A2). Emoji is the only "art" the game uses.

export const WORDS = [
  // ---- Animals ----
  { word: "cat", emoji: "🐱", theme: "animals" },
  { word: "dog", emoji: "🐶", theme: "animals" },
  { word: "pig", emoji: "🐷", theme: "animals" },
  { word: "cow", emoji: "🐮", theme: "animals" },
  { word: "fox", emoji: "🦊", theme: "animals" },
  { word: "bee", emoji: "🐝", theme: "animals" },
  { word: "owl", emoji: "🦉", theme: "animals" },
  { word: "ant", emoji: "🐜", theme: "animals" },
  { word: "bear", emoji: "🐻", theme: "animals" },
  { word: "lion", emoji: "🦁", theme: "animals" },
  { word: "frog", emoji: "🐸", theme: "animals" },
  { word: "fish", emoji: "🐟", theme: "animals" },
  { word: "duck", emoji: "🦆", theme: "animals" },
  { word: "bird", emoji: "🐦", theme: "animals" },
  { word: "crab", emoji: "🦀", theme: "animals" },
  { word: "wolf", emoji: "🐺", theme: "animals" },
  { word: "horse", emoji: "🐴", theme: "animals" },
  { word: "tiger", emoji: "🐯", theme: "animals" },
  { word: "panda", emoji: "🐼", theme: "animals" },
  { word: "sheep", emoji: "🐑", theme: "animals" },
  { word: "snake", emoji: "🐍", theme: "animals" },
  { word: "mouse", emoji: "🐭", theme: "animals" },
  { word: "whale", emoji: "🐳", theme: "animals" },
  { word: "monkey", emoji: "🐵", theme: "animals" },
  { word: "rabbit", emoji: "🐰", theme: "animals" },

  // ---- Food ----
  { word: "egg", emoji: "🥚", theme: "food" },
  { word: "pie", emoji: "🥧", theme: "food" },
  { word: "cake", emoji: "🍰", theme: "food" },
  { word: "corn", emoji: "🌽", theme: "food" },
  { word: "milk", emoji: "🥛", theme: "food" },
  { word: "rice", emoji: "🍚", theme: "food" },
  { word: "meat", emoji: "🍖", theme: "food" },
  { word: "fries", emoji: "🍟", theme: "food" },
  { word: "apple", emoji: "🍎", theme: "food" },
  { word: "bread", emoji: "🍞", theme: "food" },
  { word: "lemon", emoji: "🍋", theme: "food" },
  { word: "grape", emoji: "🍇", theme: "food" },
  { word: "peach", emoji: "🍑", theme: "food" },
  { word: "pizza", emoji: "🍕", theme: "food" },
  { word: "candy", emoji: "🍬", theme: "food" },
  { word: "donut", emoji: "🍩", theme: "food" },
  { word: "honey", emoji: "🍯", theme: "food" },
  { word: "banana", emoji: "🍌", theme: "food" },
  { word: "cherry", emoji: "🍒", theme: "food" },
  { word: "cookie", emoji: "🍪", theme: "food" },
  { word: "carrot", emoji: "🥕", theme: "food" },
  { word: "burger", emoji: "🍔", theme: "food" },

  // ---- Home ----
  { word: "bed", emoji: "🛏️", theme: "home" },
  { word: "cup", emoji: "🥤", theme: "home" },
  { word: "key", emoji: "🔑", theme: "home" },
  { word: "door", emoji: "🚪", theme: "home" },
  { word: "book", emoji: "📖", theme: "home" },
  { word: "lamp", emoji: "💡", theme: "home" },
  { word: "sofa", emoji: "🛋️", theme: "home" },
  { word: "bath", emoji: "🛁", theme: "home" },
  { word: "clock", emoji: "⏰", theme: "home" },
  { word: "chair", emoji: "🪑", theme: "home" },
  { word: "phone", emoji: "📱", theme: "home" },
  { word: "spoon", emoji: "🥄", theme: "home" },
  { word: "broom", emoji: "🧹", theme: "home" },
  { word: "plate", emoji: "🍽️", theme: "home" },
  { word: "window", emoji: "🪟", theme: "home" },
  { word: "pencil", emoji: "✏️", theme: "home" },
  { word: "candle", emoji: "🕯️", theme: "home" },

  // ---- Nature ----
  { word: "sun", emoji: "☀️", theme: "nature" },
  { word: "sea", emoji: "🌊", theme: "nature" },
  { word: "leaf", emoji: "🍃", theme: "nature" },
  { word: "moon", emoji: "🌙", theme: "nature" },
  { word: "star", emoji: "⭐", theme: "nature" },
  { word: "tree", emoji: "🌳", theme: "nature" },
  { word: "rain", emoji: "🌧️", theme: "nature" },
  { word: "snow", emoji: "❄️", theme: "nature" },
  { word: "fire", emoji: "🔥", theme: "nature" },
  { word: "rock", emoji: "🪨", theme: "nature" },
  { word: "cloud", emoji: "☁️", theme: "nature" },
  { word: "plant", emoji: "🌱", theme: "nature" },
  { word: "flower", emoji: "🌸", theme: "nature" },
  { word: "cactus", emoji: "🌵", theme: "nature" },
  { word: "rainbow", emoji: "🌈", theme: "nature" },

  // ---- Things & travel ----
  { word: "car", emoji: "🚗", theme: "things" },
  { word: "bus", emoji: "🚌", theme: "things" },
  { word: "hat", emoji: "🎩", theme: "things" },
  { word: "ball", emoji: "⚽", theme: "things" },
  { word: "bike", emoji: "🚲", theme: "things" },
  { word: "boat", emoji: "⛵", theme: "things" },
  { word: "gift", emoji: "🎁", theme: "things" },
  { word: "drum", emoji: "🥁", theme: "things" },
  { word: "kite", emoji: "🪁", theme: "things" },
  { word: "shoe", emoji: "👟", theme: "things" },
  { word: "sock", emoji: "🧦", theme: "things" },
  { word: "ring", emoji: "💍", theme: "things" },
  { word: "train", emoji: "🚆", theme: "things" },
  { word: "plane", emoji: "✈️", theme: "things" },
  { word: "clown", emoji: "🤡", theme: "things" },
  { word: "robot", emoji: "🤖", theme: "things" },
  { word: "watch", emoji: "⌚", theme: "things" },
  { word: "shirt", emoji: "👕", theme: "things" },
  { word: "crown", emoji: "👑", theme: "things" },
  { word: "camera", emoji: "📷", theme: "things" },
  { word: "guitar", emoji: "🎸", theme: "things" },
  { word: "rocket", emoji: "🚀", theme: "things" },
  { word: "umbrella", emoji: "☂️", theme: "things" },

  // ---- Body ----
  { word: "eye", emoji: "👁️", theme: "body" },
  { word: "ear", emoji: "👂", theme: "body" },
  { word: "lips", emoji: "👄", theme: "body" },
  { word: "hand", emoji: "✋", theme: "body" },
  { word: "nose", emoji: "👃", theme: "body" },
  { word: "foot", emoji: "🦶", theme: "body" },
  { word: "bone", emoji: "🦴", theme: "body" },
  { word: "tooth", emoji: "🦷", theme: "body" },
  { word: "brain", emoji: "🧠", theme: "body" },
  { word: "tongue", emoji: "👅", theme: "body" },

  // ---- Colors ----
  { word: "red", emoji: "🔴", theme: "colors" },
  { word: "blue", emoji: "🔵", theme: "colors" },
  { word: "pink", emoji: "🩷", theme: "colors" },
  { word: "green", emoji: "🟢", theme: "colors" },
  { word: "black", emoji: "⚫", theme: "colors" },
  { word: "white", emoji: "⚪", theme: "colors" },
  { word: "brown", emoji: "🟤", theme: "colors" },
  { word: "orange", emoji: "🟠", theme: "colors" },
  { word: "purple", emoji: "🟣", theme: "colors" },
  { word: "yellow", emoji: "🟡", theme: "colors" },

  // ---- Clothes ----
  { word: "cap", emoji: "🧢", theme: "clothes" },
  { word: "tie", emoji: "👔", theme: "clothes" },
  { word: "coat", emoji: "🧥", theme: "clothes" },
  { word: "boot", emoji: "🥾", theme: "clothes" },
  { word: "dress", emoji: "👗", theme: "clothes" },
  { word: "jeans", emoji: "👖", theme: "clothes" },
  { word: "scarf", emoji: "🧣", theme: "clothes" },
  { word: "glove", emoji: "🧤", theme: "clothes" },
  { word: "bikini", emoji: "👙", theme: "clothes" },

  // ---- Sports & play ----
  { word: "dice", emoji: "🎲", theme: "sports" },
  { word: "medal", emoji: "🏅", theme: "sports" },
  { word: "darts", emoji: "🎯", theme: "sports" },
  { word: "trophy", emoji: "🏆", theme: "sports" },
  { word: "tennis", emoji: "🎾", theme: "sports" },
  { word: "puzzle", emoji: "🧩", theme: "sports" },

  // ---- School ----
  { word: "bag", emoji: "🎒", theme: "school" },
  { word: "ruler", emoji: "📏", theme: "school" },
  { word: "paint", emoji: "🎨", theme: "school" },
  { word: "globe", emoji: "🌐", theme: "school" },
  { word: "crayon", emoji: "🖍️", theme: "school" },
];
