// Vocabulary data for WordPop!
// Each entry: { word, emoji, theme }
// Rules: `word` is lowercase a-z only (no spaces/hyphens), concrete & picturable,
// beginner-friendly (CEFR A1-A2). Emoji is the only "art" the game uses.

export const WORDS = [
  // ---- Animals ----
  { word: "cat", emoji: "🐱", theme: "animals" },
  { word: "dog", emoji: "🐶", theme: "animals" },
  { word: "pig", emoji: "🐷", theme: "animals" },
  { word: "cow", emoji: "🐮", theme: "animals" },
  { word: "fox", emoji: "🦊", theme: "animals" },
  { word: "bee", emoji: "🐝", theme: "animals" },
  { word: "owl", emoji: "🦉", theme: "animals" },
  { word: "ant", emoji: "🐜", theme: "animals" },
  { word: "bear", emoji: "🐻", theme: "animals" },
  { word: "lion", emoji: "🦁", theme: "animals" },
  { word: "frog", emoji: "🐸", theme: "animals" },
  { word: "fish", emoji: "🐟", theme: "animals" },
  { word: "duck", emoji: "🦆", theme: "animals" },
  { word: "bird", emoji: "🐦", theme: "animals" },
  { word: "crab", emoji: "🦀", theme: "animals" },
  { word: "wolf", emoji: "🐺", theme: "animals" },
  { word: "horse", emoji: "🐴", theme: "animals" },
  { word: "tiger", emoji: "🐯", theme: "animals" },
  { word: "panda", emoji: "🐼", theme: "animals" },
  { word: "sheep", emoji: "🐑", theme: "animals" },
  { word: "snake", emoji: "🐍", theme: "animals" },
  { word: "mouse", emoji: "🐭", theme: "animals" },
  { word: "whale", emoji: "🐳", theme: "animals" },
  { word: "monkey", emoji: "🐵", theme: "animals" },
  { word: "rabbit", emoji: "🐰", theme: "animals" },

  // ---- Food ----
  { word: "egg", emoji: "🥚", theme: "food" },
  { word: "pie", emoji: "🥧", theme: "food" },
  { word: "cake", emoji: "🍰", theme: "food" },
  { word: "corn", emoji: "🌽", theme: "food" },
  { word: "milk", emoji: "🥛", theme: "food" },
  { word: "rice", emoji: "🍚", theme: "food" },
  { word: "meat", emoji: "🍖", theme: "food" },
  { word: "fries", emoji: "🍟", theme: "food" },
  { word: "apple", emoji: "🍎", theme: "food" },
  { word: "bread", emoji: "🍞", theme: "food" },
  { word: "lemon", emoji: "🍋", theme: "food" },
  { word: "grape", emoji: "🍇", theme: "food" },
  { word: "peach", emoji: "🍑", theme: "food" },
  { word: "pizza", emoji: "🍕", theme: "food" },
  { word: "candy", emoji: "🍬", theme: "food" },
  { word: "donut", emoji: "🍩", theme: "food" },
  { word: "honey", emoji: "🍯", theme: "food" },
  { word: "banana", emoji: "🍌", theme: "food" },
  { word: "cherry", emoji: "🍒", theme: "food" },
  { word: "cookie", emoji: "🍪", theme: "food" },
  { word: "carrot", emoji: "🥕", theme: "food" },
  { word: "burger", emoji: "🍔", theme: "food" },

  // ---- Home ----
  { word: "bed", emoji: "🛏️", theme: "home" },
  { word: "cup", emoji: "🥤", theme: "home" },
  { word: "key", emoji: "🔑", theme: "home" },
  { word: "door", emoji: "🚪", theme: "home" },
  { word: "book", emoji: "📖", theme: "home" },
  { word: "lamp", emoji: "💡", theme: "home" },
  { word: "sofa", emoji: "🛋️", theme: "home" },
  { word: "bath", emoji: "🛁", theme: "home" },
  { word: "clock", emoji: "⏰", theme: "home" },
  { word: "chair", emoji: "🪑", theme: "home" },
  { word: "phone", emoji: "📱", theme: "home" },
  { word: "spoon", emoji: "🥄", theme: "home" },
  { word: "broom", emoji: "🧹", theme: "home" },
  { word: "plate", emoji: "🍽️", theme: "home" },
  { word: "window", emoji: "🪟", theme: "home" },
  { word: "pencil", emoji: "✏️", theme: "home" },
  { word: "candle", emoji: "🕯️", theme: "home" },

  // ---- Nature ----
  { word: "sun", emoji: "☀️", theme: "nature" },
  { word: "sea", emoji: "🌊", theme: "nature" },
  { word: "leaf", emoji: "🍃", theme: "nature" },
  { word: "moon", emoji: "🌙", theme: "nature" },
  { word: "star", emoji: "⭐", theme: "nature" },
  { word: "tree", emoji: "🌳", theme: "nature" },
  { word: "rain", emoji: "🌧️", theme: "nature" },
  { word: "snow", emoji: "❄️", theme: "nature" },
  { word: "fire", emoji: "🔥", theme: "nature" },
  { word: "rock", emoji: "🪨", theme: "nature" },
  { word: "cloud", emoji: "☁️", theme: "nature" },
  { word: "plant", emoji: "🌱", theme: "nature" },
  { word: "flower", emoji: "🌸", theme: "nature" },
  { word: "cactus", emoji: "🌵", theme: "nature" },
  { word: "rainbow", emoji: "🌈", theme: "nature" },

  // ---- Things & travel ----
  { word: "car", emoji: "🚗", theme: "things" },
  { word: "bus", emoji: "🚌", theme: "things" },
  { word: "hat", emoji: "🎩", theme: "things" },
  { word: "ball", emoji: "⚽", theme: "things" },
  { word: "bike", emoji: "🚲", theme: "things" },
  { word: "boat", emoji: "⛵", theme: "things" },
  { word: "gift", emoji: "🎁", theme: "things" },
  { word: "drum", emoji: "🥁", theme: "things" },
  { word: "kite", emoji: "🪁", theme: "things" },
  { word: "shoe", emoji: "👟", theme: "things" },
  { word: "sock", emoji: "🧦", theme: "things" },
  { word: "ring", emoji: "💍", theme: "things" },
  { word: "train", emoji: "🚆", theme: "things" },
  { word: "plane", emoji: "✈️", theme: "things" },
  { word: "clown", emoji: "🤡", theme: "things" },
  { word: "robot", emoji: "🤖", theme: "things" },
  { word: "watch", emoji: "⌚", theme: "things" },
  { word: "shirt", emoji: "👕", theme: "things" },
  { word: "crown", emoji: "👑", theme: "things" },
  { word: "camera", emoji: "📷", theme: "things" },
  { word: "guitar", emoji: "🎸", theme: "things" },
  { word: "rocket", emoji: "🚀", theme: "things" },
  { word: "umbrella", emoji: "☂️", theme: "things" },

  // ---- Body ----
  { word: "eye", emoji: "👁️", theme: "body" },
  { word: "ear", emoji: "👂", theme: "body" },
  { word: "lips", emoji: "👄", theme: "body" },
  { word: "hand", emoji: "✋", theme: "body" },
  { word: "nose", emoji: "👃", theme: "body" },
  { word: "foot", emoji: "🦶", theme: "body" },
  { word: "bone", emoji: "🦴", theme: "body" },
  { word: "tooth", emoji: "🦷", theme: "body" },
  { word: "brain", emoji: "🧠", theme: "body" },
  { word: "tongue", emoji: "👅", theme: "body" },

  // ---- Colors ----
  { word: "red", emoji: "🔴", theme: "colors" },
  { word: "blue", emoji: "🔵", theme: "colors" },
  { word: "pink", emoji: "🩷", theme: "colors" },
  { word: "green", emoji: "🟢", theme: "colors" },
  { word: "black", emoji: "⚫", theme: "colors" },
  { word: "white", emoji: "⚪", theme: "colors" },
  { word: "brown", emoji: "🟤", theme: "colors" },
  { word: "orange", emoji: "🟠", theme: "colors" },
  { word: "purple", emoji: "🟣", theme: "colors" },
  { word: "yellow", emoji: "🟡", theme: "colors" },

  // ---- Clothes ----
  { word: "cap", emoji: "🧢", theme: "clothes" },
  { word: "tie", emoji: "👔", theme: "clothes" },
  { word: "coat", emoji: "🧥", theme: "clothes" },
  { word: "boot", emoji: "🥾", theme: "clothes" },
  { word: "dress", emoji: "👗", theme: "clothes" },
  { word: "jeans", emoji: "👖", theme: "clothes" },
  { word: "scarf", emoji: "🧣", theme: "clothes" },
  { word: "glove", emoji: "🧤", theme: "clothes" },
  { word: "bikini", emoji: "👙", theme: "clothes" },

  // ---- Sports & play ----
  { word: "dice", emoji: "🎲", theme: "sports" },
  { word: "medal", emoji: "🏅", theme: "sports" },
  { word: "darts", emoji: "🎯", theme: "sports" },
  { word: "trophy", emoji: "🏆", theme: "sports" },
  { word: "tennis", emoji: "🎾", theme: "sports" },
  { word: "puzzle", emoji: "🧩", theme: "sports" },

  // ---- School ----
  { word: "bag", emoji: "🎒", theme: "school" },
  { word: "ruler", emoji: "📏", theme: "school" },
  { word: "paint", emoji: "🎨", theme: "school" },
  { word: "globe", emoji: "🌐", theme: "school" },
  { word: "crayon", emoji: "🖍️", theme: "school" },

  // ---- Animals (extended) ----
  { word: "goat", emoji: "🐐", theme: "animals" },
  { word: "hen", emoji: "🐔", theme: "animals" },
  { word: "chick", emoji: "🐤", theme: "animals" },
  { word: "swan", emoji: "🦢", theme: "animals" },
  { word: "eagle", emoji: "🦅", theme: "animals" },
  { word: "shark", emoji: "🦈", theme: "animals" },
  { word: "snail", emoji: "🐌", theme: "animals" },
  { word: "worm", emoji: "🪱", theme: "animals" },
  { word: "spider", emoji: "🕷️", theme: "animals" },
  { word: "turtle", emoji: "🐢", theme: "animals" },
  { word: "lizard", emoji: "🦎", theme: "animals" },
  { word: "camel", emoji: "🐫", theme: "animals" },
  { word: "zebra", emoji: "🦓", theme: "animals" },
  { word: "deer", emoji: "🦌", theme: "animals" },
  { word: "koala", emoji: "🐨", theme: "animals" },
  { word: "bat", emoji: "🦇", theme: "animals" },
  { word: "dove", emoji: "🕊️", theme: "animals" },
  { word: "parrot", emoji: "🦜", theme: "animals" },
  { word: "penguin", emoji: "🐧", theme: "animals" },
  { word: "seal", emoji: "🦭", theme: "animals" },
  { word: "otter", emoji: "🦦", theme: "animals" },
  { word: "octopus", emoji: "🐙", theme: "animals" },
  { word: "shrimp", emoji: "🦐", theme: "animals" },
  { word: "dolphin", emoji: "🐬", theme: "animals" },
  { word: "ladybug", emoji: "🐞", theme: "animals" },
  { word: "rat", emoji: "🐀", theme: "animals" },
  { word: "hamster", emoji: "🐹", theme: "animals" },
  { word: "dragon", emoji: "🐉", theme: "animals" },
  { word: "unicorn", emoji: "🦄", theme: "animals" },
  { word: "elephant", emoji: "🐘", theme: "animals" },
  { word: "giraffe", emoji: "🦒", theme: "animals" },
  { word: "rhino", emoji: "🦏", theme: "animals" },
  { word: "hippo", emoji: "🦛", theme: "animals" },
  { word: "gorilla", emoji: "🦍", theme: "animals" },
  { word: "llama", emoji: "🦙", theme: "animals" },
  { word: "sloth", emoji: "🦥", theme: "animals" },
  { word: "beaver", emoji: "🦫", theme: "animals" },
  { word: "skunk", emoji: "🦨", theme: "animals" },
  { word: "badger", emoji: "🦡", theme: "animals" },
  { word: "bison", emoji: "🦬", theme: "animals" },
  { word: "scorpion", emoji: "🦂", theme: "animals" },
  { word: "butterfly", emoji: "🦋", theme: "animals" },
  { word: "dinosaur", emoji: "🦕", theme: "animals" },
  { word: "kangaroo", emoji: "🦘", theme: "animals" },
  { word: "peacock", emoji: "🦚", theme: "animals" },
  { word: "flamingo", emoji: "🦩", theme: "animals" },
  { word: "lobster", emoji: "🦞", theme: "animals" },
  { word: "beetle", emoji: "🪲", theme: "animals" },
  { word: "fly", emoji: "🪰", theme: "animals" },
  { word: "mosquito", emoji: "🦟", theme: "animals" },
  { word: "bull", emoji: "🐂", theme: "animals" },
  { word: "ram", emoji: "🐏", theme: "animals" },

  // ---- Food (extended) ----
  { word: "taco", emoji: "🌮", theme: "food" },
  { word: "pear", emoji: "🍐", theme: "food" },
  { word: "melon", emoji: "🍈", theme: "food" },
  { word: "mango", emoji: "🥭", theme: "food" },
  { word: "kiwi", emoji: "🥝", theme: "food" },
  { word: "olive", emoji: "🫒", theme: "food" },
  { word: "onion", emoji: "🧅", theme: "food" },
  { word: "garlic", emoji: "🧄", theme: "food" },
  { word: "potato", emoji: "🥔", theme: "food" },
  { word: "tomato", emoji: "🍅", theme: "food" },
  { word: "pepper", emoji: "🌶️", theme: "food" },
  { word: "salad", emoji: "🥗", theme: "food" },
  { word: "soup", emoji: "🍲", theme: "food" },
  { word: "steak", emoji: "🥩", theme: "food" },
  { word: "bacon", emoji: "🥓", theme: "food" },
  { word: "chicken", emoji: "🍗", theme: "food" },
  { word: "sushi", emoji: "🍣", theme: "food" },
  { word: "noodles", emoji: "🍜", theme: "food" },
  { word: "pasta", emoji: "🍝", theme: "food" },
  { word: "sandwich", emoji: "🥪", theme: "food" },
  { word: "popcorn", emoji: "🍿", theme: "food" },
  { word: "pretzel", emoji: "🥨", theme: "food" },
  { word: "pancake", emoji: "🥞", theme: "food" },
  { word: "waffle", emoji: "🧇", theme: "food" },
  { word: "cheese", emoji: "🧀", theme: "food" },
  { word: "butter", emoji: "🧈", theme: "food" },
  { word: "cupcake", emoji: "🧁", theme: "food" },
  { word: "chocolate", emoji: "🍫", theme: "food" },
  { word: "lollipop", emoji: "🍭", theme: "food" },
  { word: "juice", emoji: "🧃", theme: "food" },
  { word: "water", emoji: "💧", theme: "food" },
  { word: "tea", emoji: "🍵", theme: "food" },
  { word: "coffee", emoji: "☕", theme: "food" },
  { word: "salt", emoji: "🧂", theme: "food" },
  { word: "coconut", emoji: "🥥", theme: "food" },
  { word: "avocado", emoji: "🥑", theme: "food" },
  { word: "broccoli", emoji: "🥦", theme: "food" },
  { word: "cucumber", emoji: "🥒", theme: "food" },
  { word: "mushroom", emoji: "🍄", theme: "food" },
  { word: "peanut", emoji: "🥜", theme: "food" },
  { word: "hotdog", emoji: "🌭", theme: "food" },
  { word: "bagel", emoji: "🥯", theme: "food" },
  { word: "croissant", emoji: "🥐", theme: "food" },
  { word: "baguette", emoji: "🥖", theme: "food" },
  { word: "dumpling", emoji: "🥟", theme: "food" },
  { word: "burrito", emoji: "🌯", theme: "food" },
  { word: "curry", emoji: "🍛", theme: "food" },
  { word: "sundae", emoji: "🍨", theme: "food" },
  { word: "pudding", emoji: "🍮", theme: "food" },
  { word: "chestnut", emoji: "🌰", theme: "food" },

  // ---- Home (extended) ----
  { word: "house", emoji: "🏠", theme: "home" },
  { word: "knife", emoji: "🔪", theme: "home" },
  { word: "bowl", emoji: "🥣", theme: "home" },
  { word: "lock", emoji: "🔒", theme: "home" },
  { word: "soap", emoji: "🧼", theme: "home" },
  { word: "sponge", emoji: "🧽", theme: "home" },
  { word: "mirror", emoji: "🪞", theme: "home" },
  { word: "ladder", emoji: "🪜", theme: "home" },
  { word: "radio", emoji: "📻", theme: "home" },
  { word: "laptop", emoji: "💻", theme: "home" },
  { word: "battery", emoji: "🔋", theme: "home" },
  { word: "plug", emoji: "🔌", theme: "home" },
  { word: "bell", emoji: "🔔", theme: "home" },
  { word: "box", emoji: "📦", theme: "home" },
  { word: "basket", emoji: "🧺", theme: "home" },
  { word: "bucket", emoji: "🪣", theme: "home" },
  { word: "trash", emoji: "🗑️", theme: "home" },
  { word: "toilet", emoji: "🚽", theme: "home" },
  { word: "shower", emoji: "🚿", theme: "home" },
  { word: "scissors", emoji: "✂️", theme: "home" },
  { word: "needle", emoji: "🪡", theme: "home" },
  { word: "thread", emoji: "🧵", theme: "home" },
  { word: "brush", emoji: "🖌️", theme: "home" },
  { word: "fork", emoji: "🍴", theme: "home" },
  { word: "hammer", emoji: "🔨", theme: "home" },
  { word: "wrench", emoji: "🔧", theme: "home" },
  { word: "screw", emoji: "🔩", theme: "home" },
  { word: "saw", emoji: "🪚", theme: "home" },
  { word: "chain", emoji: "⛓️", theme: "home" },
  { word: "lantern", emoji: "🏮", theme: "home" },

  // ---- Nature (extended) ----
  { word: "wind", emoji: "🌬️", theme: "nature" },
  { word: "storm", emoji: "⛈️", theme: "nature" },
  { word: "fog", emoji: "🌫️", theme: "nature" },
  { word: "ice", emoji: "🧊", theme: "nature" },
  { word: "mountain", emoji: "⛰️", theme: "nature" },
  { word: "volcano", emoji: "🌋", theme: "nature" },
  { word: "desert", emoji: "🏜️", theme: "nature" },
  { word: "island", emoji: "🏝️", theme: "nature" },
  { word: "beach", emoji: "🏖️", theme: "nature" },
  { word: "forest", emoji: "🌲", theme: "nature" },
  { word: "clover", emoji: "🍀", theme: "nature" },
  { word: "rose", emoji: "🌹", theme: "nature" },
  { word: "tulip", emoji: "🌷", theme: "nature" },
  { word: "sunflower", emoji: "🌻", theme: "nature" },
  { word: "daisy", emoji: "🌼", theme: "nature" },
  { word: "palm", emoji: "🌴", theme: "nature" },
  { word: "earth", emoji: "🌍", theme: "nature" },
  { word: "space", emoji: "🌌", theme: "nature" },
  { word: "comet", emoji: "☄️", theme: "nature" },
  { word: "planet", emoji: "🪐", theme: "nature" },
  { word: "snowman", emoji: "☃️", theme: "nature" },
  { word: "sunrise", emoji: "🌅", theme: "nature" },
  { word: "sunset", emoji: "🌇", theme: "nature" },
  { word: "night", emoji: "🌃", theme: "nature" },
  { word: "shell", emoji: "🐚", theme: "nature" },
  { word: "feather", emoji: "🪶", theme: "nature" },
  { word: "maple", emoji: "🍁", theme: "nature" },
  { word: "bamboo", emoji: "🎋", theme: "nature" },
  { word: "herb", emoji: "🌿", theme: "nature" },
  { word: "wheat", emoji: "🌾", theme: "nature" },
  { word: "tornado", emoji: "🌪️", theme: "nature" },

  // ---- Body (extended) ----
  { word: "arm", emoji: "💪", theme: "body" },
  { word: "leg", emoji: "🦵", theme: "body" },
  { word: "finger", emoji: "👆", theme: "body" },
  { word: "thumb", emoji: "👍", theme: "body" },
  { word: "heart", emoji: "❤️", theme: "body" },
  { word: "lung", emoji: "🫁", theme: "body" },
  { word: "skull", emoji: "💀", theme: "body" },
  { word: "nail", emoji: "💅", theme: "body" },
  { word: "beard", emoji: "🧔", theme: "body" },

  // ---- Clothes (extended) ----
  { word: "shorts", emoji: "🩳", theme: "clothes" },
  { word: "swimsuit", emoji: "🩱", theme: "clothes" },
  { word: "sandal", emoji: "👡", theme: "clothes" },
  { word: "heel", emoji: "👠", theme: "clothes" },
  { word: "purse", emoji: "👛", theme: "clothes" },
  { word: "glasses", emoji: "👓", theme: "clothes" },
  { word: "helmet", emoji: "⛑️", theme: "clothes" },
  { word: "mask", emoji: "😷", theme: "clothes" },
  { word: "kimono", emoji: "👘", theme: "clothes" },
  { word: "sari", emoji: "🥻", theme: "clothes" },

  // ---- Sports (extended) ----
  { word: "cricket", emoji: "🏏", theme: "sports" },
  { word: "football", emoji: "🏈", theme: "sports" },
  { word: "rugby", emoji: "🏉", theme: "sports" },
  { word: "baseball", emoji: "⚾", theme: "sports" },
  { word: "golf", emoji: "⛳", theme: "sports" },
  { word: "bowling", emoji: "🎳", theme: "sports" },
  { word: "boxing", emoji: "🥊", theme: "sports" },
  { word: "skate", emoji: "⛸️", theme: "sports" },
  { word: "ski", emoji: "🎿", theme: "sports" },
  { word: "swim", emoji: "🏊", theme: "sports" },
  { word: "kayak", emoji: "🛶", theme: "sports" },
  { word: "fishing", emoji: "🎣", theme: "sports" },
  { word: "arrow", emoji: "🏹", theme: "sports" },
  { word: "badminton", emoji: "🏸", theme: "sports" },
  { word: "hockey", emoji: "🏒", theme: "sports" },
  { word: "yoga", emoji: "🧘", theme: "sports" },
  { word: "dance", emoji: "💃", theme: "sports" },
  { word: "climb", emoji: "🧗", theme: "sports" },
  { word: "basketball", emoji: "🏀", theme: "sports" },
  { word: "volleyball", emoji: "🏐", theme: "sports" },

  // ---- School (extended) ----
  { word: "pen", emoji: "🖊️", theme: "school" },
  { word: "paper", emoji: "📄", theme: "school" },
  { word: "note", emoji: "📝", theme: "school" },
  { word: "clip", emoji: "📎", theme: "school" },
  { word: "pin", emoji: "📌", theme: "school" },
  { word: "folder", emoji: "📁", theme: "school" },
  { word: "letter", emoji: "✉️", theme: "school" },
  { word: "map", emoji: "🗺️", theme: "school" },
  { word: "number", emoji: "🔢", theme: "school" },
  { word: "alphabet", emoji: "🔤", theme: "school" },
  { word: "telescope", emoji: "🔭", theme: "school" },
  { word: "magnet", emoji: "🧲", theme: "school" },
  { word: "printer", emoji: "🖨️", theme: "school" },
  { word: "calendar", emoji: "📅", theme: "school" },
  { word: "timer", emoji: "⏲️", theme: "school" },

  // ---- Transport ----
  { word: "taxi", emoji: "🚕", theme: "transport" },
  { word: "truck", emoji: "🚚", theme: "transport" },
  { word: "van", emoji: "🚐", theme: "transport" },
  { word: "jeep", emoji: "🚙", theme: "transport" },
  { word: "ambulance", emoji: "🚑", theme: "transport" },
  { word: "tractor", emoji: "🚜", theme: "transport" },
  { word: "scooter", emoji: "🛵", theme: "transport" },
  { word: "ship", emoji: "🚢", theme: "transport" },
  { word: "ferry", emoji: "⛴️", theme: "transport" },
  { word: "subway", emoji: "🚇", theme: "transport" },
  { word: "tram", emoji: "🚊", theme: "transport" },
  { word: "sled", emoji: "🛷", theme: "transport" },
  { word: "anchor", emoji: "⚓", theme: "transport" },
  { word: "fuel", emoji: "⛽", theme: "transport" },
  { word: "traffic", emoji: "🚦", theme: "transport" },
  { word: "bridge", emoji: "🌉", theme: "transport" },
  { word: "road", emoji: "🛣️", theme: "transport" },
  { word: "station", emoji: "🚉", theme: "transport" },
  { word: "helicopter", emoji: "🚁", theme: "transport" },

  // ---- Places ----
  { word: "school", emoji: "🏫", theme: "places" },
  { word: "hospital", emoji: "🏥", theme: "places" },
  { word: "bank", emoji: "🏦", theme: "places" },
  { word: "hotel", emoji: "🏨", theme: "places" },
  { word: "shop", emoji: "🏪", theme: "places" },
  { word: "office", emoji: "🏢", theme: "places" },
  { word: "factory", emoji: "🏭", theme: "places" },
  { word: "castle", emoji: "🏰", theme: "places" },
  { word: "church", emoji: "⛪", theme: "places" },
  { word: "mosque", emoji: "🕌", theme: "places" },
  { word: "temple", emoji: "🛕", theme: "places" },
  { word: "park", emoji: "🏞️", theme: "places" },
  { word: "circus", emoji: "🎪", theme: "places" },
  { word: "museum", emoji: "🏛️", theme: "places" },
  { word: "city", emoji: "🏙️", theme: "places" },
  { word: "village", emoji: "🏘️", theme: "places" },
  { word: "tent", emoji: "⛺", theme: "places" },
  { word: "stadium", emoji: "🏟️", theme: "places" },

  // ---- People ----
  { word: "baby", emoji: "👶", theme: "people" },
  { word: "boy", emoji: "👦", theme: "people" },
  { word: "girl", emoji: "👧", theme: "people" },
  { word: "man", emoji: "👨", theme: "people" },
  { word: "woman", emoji: "👩", theme: "people" },
  { word: "king", emoji: "🤴", theme: "people" },
  { word: "queen", emoji: "👸", theme: "people" },
  { word: "police", emoji: "👮", theme: "people" },
  { word: "worker", emoji: "👷", theme: "people" },
  { word: "guard", emoji: "💂", theme: "people" },
  { word: "ninja", emoji: "🥷", theme: "people" },
  { word: "santa", emoji: "🎅", theme: "people" },
  { word: "angel", emoji: "👼", theme: "people" },
  { word: "doctor", emoji: "🧑‍⚕️", theme: "people" },
  { word: "teacher", emoji: "🧑‍🏫", theme: "people" },
  { word: "farmer", emoji: "🧑‍🌾", theme: "people" },
  { word: "cook", emoji: "🧑‍🍳", theme: "people" },
  { word: "pilot", emoji: "🧑‍✈️", theme: "people" },
  { word: "singer", emoji: "🧑‍🎤", theme: "people" },

  // ---- Feelings ----
  { word: "happy", emoji: "😀", theme: "feelings" },
  { word: "sad", emoji: "😢", theme: "feelings" },
  { word: "angry", emoji: "😠", theme: "feelings" },
  { word: "tired", emoji: "😴", theme: "feelings" },
  { word: "scared", emoji: "😨", theme: "feelings" },
  { word: "sick", emoji: "🤒", theme: "feelings" },
  { word: "love", emoji: "🥰", theme: "feelings" },
  { word: "laugh", emoji: "😂", theme: "feelings" },
  { word: "cry", emoji: "😭", theme: "feelings" },
  { word: "smile", emoji: "😊", theme: "feelings" },
  { word: "shy", emoji: "😳", theme: "feelings" },
  { word: "cool", emoji: "😎", theme: "feelings" },
  { word: "bored", emoji: "🥱", theme: "feelings" },
  { word: "hungry", emoji: "🤤", theme: "feelings" },
  { word: "sleepy", emoji: "😪", theme: "feelings" },
  { word: "confused", emoji: "😕", theme: "feelings" },

  // ---- Music ----
  { word: "piano", emoji: "🎹", theme: "music" },
  { word: "violin", emoji: "🎻", theme: "music" },
  { word: "trumpet", emoji: "🎺", theme: "music" },
  { word: "saxophone", emoji: "🎷", theme: "music" },
  { word: "banjo", emoji: "🪕", theme: "music" },
  { word: "music", emoji: "🎵", theme: "music" },
  { word: "song", emoji: "🎶", theme: "music" },
  { word: "headphone", emoji: "🎧", theme: "music" },
  { word: "speaker", emoji: "🔊", theme: "music" },
  { word: "microphone", emoji: "🎤", theme: "music" },

  // ---- Things (extended) ----
  { word: "balloon", emoji: "🎈", theme: "things" },
  { word: "ribbon", emoji: "🎀", theme: "things" },
  { word: "teddy", emoji: "🧸", theme: "things" },
  { word: "yoyo", emoji: "🪀", theme: "things" },
  { word: "lipstick", emoji: "💄", theme: "things" },
  { word: "diamond", emoji: "💎", theme: "things" },
  { word: "money", emoji: "💵", theme: "things" },
  { word: "coin", emoji: "🪙", theme: "things" },
  { word: "card", emoji: "💳", theme: "things" },
  { word: "ticket", emoji: "🎫", theme: "things" },
  { word: "shield", emoji: "🛡️", theme: "things" },
  { word: "sword", emoji: "⚔️", theme: "things" },
  { word: "torch", emoji: "🔦", theme: "things" },
];
